### PR TITLE
Update property_panel.gd

### PR DESCRIPTION
**Pull request by scgm0**

### CODE REVIEW

**Review by Jummit — APPROVED** [review]
Adding an explanation or a descriptive title to the PR would be helpful, but this seems like it makes sense.

**Comment by scgm0** [comment]
> Adding an explanation or a descriptive title to the PR would be helpful, but this seems like it makes sense.在 PR 中添加解释或描述性标题会有所帮助，但这似乎是有道理的。

My presentation skills and English are very poor, so I don't know how I should explain the pr content...

**Comment by Jummit** [comment]
> > Adding an explanation or a descriptive title to the PR would be helpful, but this seems like it makes sense.在 PR 中添加解释或描述性标题会有所帮助，但这似乎是有道理的。
> 
> My presentation skills and English are very poor, so I don't know how I should explain the pr content...

No worries, it's not a problem. Also, thanks for the pull requests! It's good to see that my work is being used.

**Comment by scgm0** [comment]
> > > Adding an explanation or a descriptive title to the PR would be helpful, but this seems like it makes sense.在 PR 中添加解释或描述性标题会有所帮助，但这似乎是有道理的。
> > 
> > 
> > My presentation skills and English are very poor, so I don't know how I should explain the pr content...我的presentation skill和英语很差，所以我不知道应该怎么解释pr的内容。。。
> 
> No worries, it's not a problem. Also, thanks for the pull requests! It's good to see that my work is being used.别担心，这不是问题。另外，感谢您的拉取请求！很高兴看到我的作品被使用。

Your work is also very useful, I am happy to help

**Pull request merged**
